# Generated by Django 4.1.1 on 2022-10-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='weekDays',
            field=models.IntegerField(choices=[(1, 'Domingo'), (2, 'Segunda'), (3, 'Terca'), (4, 'Quarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Sabado')]),
        ),
    ]
