# Generated by Django 4.1.1 on 2022-10-04 03:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_ad_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='weekDays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Domingo'), (2, 'SEGUNDA'), (3, 'TERCA'), (4, 'QUARTA'), (5, 'QUINTA'), (6, 'SEXTA'), (7, 'SABADO')], max_length=7),
        ),
    ]
